info:
  name: SpringBoot Base
  description: Base project for spring boot apps.
  version: ${info.build.version}

spring:
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
